# Generated by Django 5.2.7 on 2025-10-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
