# Generated by Django 5.2.7 on 2025-10-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_customer_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
    ]
