# Generated by Django 5.2.7 on 2025-10-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_alter_customer_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid_on_time',
            field=models.BooleanField(default=True),
        ),
    ]
